### ISSUE TITLE
function 3 may not output a correct result

### ISSUE THREAD

**Issue by endvroy** [ds-g01/project1#2]
I haven't understood your implementation yet, but from your description:
```C
/********************************************************************************
 *  --------------------------------------------------------------------------------
 *  Func3 : O(N^3)
 *   	In each iteration, This algorithm firstly calculate the sum of elements in the 
 *   	same column, and then put the result of N column into an one-dimension 
 *   	array (call it temp[N]), then use an O(N) algorithm to get the maximum subarray 
 *   	of temp[N] . So the time complexity is (N+N) * N * (N+1)/2.
 *
 * 
 *********************************************************************************/
```
**I don't think this function will output a correct result. What if the matrix and the maximum subarrays of each row (shown in brackets) are:**
[1 2 3]
-2 [3 1]
[1 3] -4
**and don't form a submatrix at all?**

**Comment by woodfrog** [comment]
Using your example, in the first iteration temp[3] will be [1,2,3] ,then ThisSum will be 6. in next iteration,  temp[3] will be [1,5,4] (add the second row to temp[3]) , ThisSum will be 10 and refresh MaxSum. Then temp[3]  will be [0,8,0],   [-2,3,1]  [-1 6 -3] and finally [1 3 -4].
The iterations will be implemented for 3+2+1=6 times and in each iteration using the O(N) subfunction to get result. 
I will improve the comment later.
